version: '3'

# this is local dev file, prod need modifications

services:
  backend:
    container_name: backend
    build: ./be
    restart: always
    volumes:
      - './be:/app'
      - '/be/db.sqlite3'
    ports:
      - 8000:8000
    env_file:
      - ./be/dev-variables.env
    entrypoint: ./dev-entrypoint.sh

  frontend:
    container_name: frontend
    build: ./fe
    restart: always
    volumes:
      - './fe:/app'
      - '/fe/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
