version: '3'

# this is local dev file, prod need modifications

services:
  backend:
    container_name: backend
    build: ./be
    volumes:
      - './be:/app'
      - '/be/db.sqlite3'
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=be.dev_settings
      - SECRET_KEY=secret-key-goes-here
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    container_name: frontend
    build: ./fe
    volumes:
      - './fe:/app'
      - '/fe/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
