# Generated by Django 4.2.3 on 2023-07-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(default=None, max_length=256, null=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('deleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
