# Generated by Django 4.2.3 on 2023-07-22 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name',
                 models.CharField(max_length=256, validators=[django.core.validators.MinValueValidator(2)])),
                ('last_name',
                 models.CharField(max_length=256, validators=[django.core.validators.MinValueValidator(2)])),
                ('middle_name', models.CharField(default=None, max_length=256, null=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
