# Generated by Django 4.2.3 on 2023-07-22 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, validators=[django.core.validators.MinValueValidator(2)])),
                ('deleted', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(related_name='course', to='student.student')),
            ],
        ),
    ]
