# Generated by Django 4.2.3 on 2023-07-23 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
