# Generated by Django 4.2.3 on 2023-07-23 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0003_alter_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
